workflows:
  simulator-native-ios:
    name: iOS simulator build
    max_build_duration: 120
    instance_type: mac_mini
    environment:
      vars:
        XCODE_WORKSPACE: NewsUncle.xcworkspace
        XCODE_SCHEME: NewsUncle
        BUNDLE_ID: "io.codemagic.swiftqube"
        SONAR_TOKEN: 993037d97cc532f2f2af0568375560cf1c1dbb59
        SONAR_PROJECT_KEY: TeaTalkInternal_NewsUncle
        SONAR_ORG_KEY: teatalkinternal
      xcode: 13
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          pod install
      - name: Build ipa for distribution
        script: >
          xcodebuild build -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME"
          -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone
          12 mini,OS=15.2' -configuration Debug CODE_SIGN_IDENTITY=""
          CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - kevinvishal347@gmail.com
          - tri.zed@gmail.com
